<?php
/**
 * Created by PhpStorm.
 * User: Costa
 * Date: 26/06/2019
 * Time: 12:03
 */

namespace ThatsIt\Exception;

use Throwable;

/**
 * Class PlatformException - everything that can be caused by entities that are not
 *                           the end-user (client)
 * @package ThatsIt\Exception
 *
 * @SEE all error codes available to understand the type of problems this exception handles
 *
 * @IMPORTANT: exceptions that inherits from this one will return to the client with
 *             the 500 error page and always with the same sentence available to print
 *             (see variable $error in View/Error/error500.php - page generated by the framework)
 */
class PlatformException extends \Exception
{
    /**
     * for undefined errors
     */
    const ERROR_UNDEFINED = 0;
    
    /**
     * some resource was not found, but probably was caused by going to a wrong url
     */
    const ERROR_NOT_FOUND_SOFT = 1;
    
    /**
     * some resource was not found, but in this case some page is not accessible
     */
    const ERROR_NOT_FOUND_DANGER = 1;
    
    /**
     * indicate problems with the response given by controller
     */
    const ERROR_RESPONSE = 2;
    
    /**
     * problems related to database
     */
    const ERROR_DB = 3;
    
    /**
     * when a config file it was needed but it was missing
     */
    const ERROR_CONFIG_FILE_MISSING = 4;
    
    /**
     * when a curl request fails
     */
    const ERROR_CURL_REQUEST = 5;
    
    /**
     * PlatformException constructor.
     * @param string $message
     * @param int $code
     * @param Throwable|null $previous
     */
    public function __construct(string $message, int $code, Throwable $previous = null)
    {
        parent::__construct($message, $code, $previous);
    }
}